name: App Image Build

on:
  push:
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: Build Docker Image
        run: docker build -t local/test-build:latest -f build-base/Dockerfile build-base
      -
        name: See all docker images
        run: docker images
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker build and push
        id: build-backend
        uses: docker/build-push-action@v5
        with:
          context: build-app
          platforms: linux/amd64
          outputs: type=image,name=local/test-app,push=false
      -
        name: View docker images
        run: docker images