name: App Image Build

on:
  push:
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: build-base
          tags: myimage:latest
          outputs: type=tar,dest=/tmp/myimage.tar
      -
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: base-image
          path: /tmp/myimage.tar

  build-app:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: base-image
          path: /tmp/myimage.tar
      -
        name: ls /tmp
        run: ls /tmp
      -
        name: Load image
        run: |
          docker load -i /tmp/myimage.tar
          docker image ls -a    
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker build and push
        id: build-backend
        uses: docker/build-push-action@v5
        with:
          context: build-app
          platforms: linux/amd64
          outputs: type=image,name=etknorr/build-app,push=false