name: App Image Build

on:
  push:
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: Build Docker Image
        run: docker build -t local/ignition-base:latest -f build-base/Dockerfile build-base
      -
        name: Save Docker Image
        run: |
          mkdir -p package
          docker save local/ignition-base:latest > package/image.tar
      -
        name: Create tarball to preserve permissions
        run: |
          tar -cvf package.tar package/
      -
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: base-image
          path: package.tar

  build-app:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      -
        name: Checkout Repository
        uses: actions/checkout@v4
      -
        name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: base-image
      -
        name: See all the files
        run: ls -lah
      -
        name: See all docker images
        run: docker images
      -
        name: Export base-image tar
        run: |
          tar -xvf package.tar
      -
        name: Load Docker Image
        run: |
            docker load < package/image.tar
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker build and push
        id: build-backend
        uses: docker/build-push-action@v5
        with:
          context: build-app
          platforms: linux/amd64
          outputs: type=image,name=etknorr/build-app,push=false